
INSERT INTO "images" (id, product_name) VALUES (1, 'Black Leather Sofa');
INSERT INTO "images" (id, product_name) VALUES (2, 'King Size Memory Foam Mattress');
INSERT INTO "images" (id, product_name) VALUES (3, 'Folding Table');
INSERT INTO "images" (id, product_name) VALUES (4, 'Globe of the world');
INSERT INTO "images" (id, product_name) VALUES (5, 'Bookshelf');
INSERT INTO "images" (id, product_name) VALUES (6, 'Wood Dining Chair');
INSERT INTO "images" (id, product_name) VALUES (7, 'Wood Dining Table');
INSERT INTO "images" (id, product_name) VALUES (8, 'Water Bed');
INSERT INTO "images" (id, product_name) VALUES (9, 'Bean Bag');
INSERT INTO "images" (id, product_name) VALUES (10, 'Night Stand');
INSERT INTO "images" (id, product_name) VALUES (11, 'Desk Lamp');
INSERT INTO "images" (id, product_name) VALUES (12, 'Wall Mirror');
INSERT INTO "images" (id, product_name) VALUES (13, 'Bed Sheets');
INSERT INTO "images" (id, product_name) VALUES (14, 'Comforter');
INSERT INTO "images" (id, product_name) VALUES (15, 'Pillow');
INSERT INTO "images" (id, product_name) VALUES (16, 'Plastic Fern');
INSERT INTO "images" (id, product_name) VALUES (17, 'Lava Lamp');
INSERT INTO "images" (id, product_name) VALUES (18, 'Shag Rug');
INSERT INTO "images" (id, product_name) VALUES (19, 'Disco Ball');
INSERT INTO "images" (id, product_name) VALUES (20, 'Strobe Light');
INSERT INTO "images" (id, product_name) VALUES (21, 'Pinball Machine');
INSERT INTO "images" (id, product_name) VALUES (22, 'Ping Pong Table');
INSERT INTO "images" (id, product_name) VALUES (23, 'Dresser');
INSERT INTO "images" (id, product_name) VALUES (24, 'Grandfather Clock');
INSERT INTO "images" (id, product_name) VALUES (25, 'Foosball Table');
INSERT INTO "images" (id, product_name) VALUES (26, 'Office Chair');
INSERT INTO "images" (id, product_name) VALUES (27, 'Cinnamon Scented Candle');
INSERT INTO "images" (id, product_name) VALUES (28, 'Blue Throw Pillow');
INSERT INTO "images" (id, product_name) VALUES (29, 'Garlic Press');
INSERT INTO "images" (id, product_name) VALUES (30, 'Kitchen Timer');
INSERT INTO "images" (id, product_name) VALUES (31, 'Plastic Cutlery');
INSERT INTO "images" (id, product_name) VALUES (32, 'Stainless Steel Refrigerator');
INSERT INTO "images" (id, product_name) VALUES (33, 'Sporks');
INSERT INTO "images" (id, product_name) VALUES (34, 'Salt and Pepper Shakers');
INSERT INTO "images" (id, product_name) VALUES (35, 'Moist Toilettes');
INSERT INTO "images" (id, product_name) VALUES (36, 'Toothpicks');
INSERT INTO "images" (id, product_name) VALUES (37, 'Microwave');
INSERT INTO "images" (id, product_name) VALUES (38, 'Blender');
INSERT INTO "images" (id, product_name) VALUES (39, 'Personal Grill');
INSERT INTO "images" (id, product_name) VALUES (40, 'Oven Mitts');
INSERT INTO "images" (id, product_name) VALUES (41, 'Dish Soap');
INSERT INTO "images" (id, product_name) VALUES (42, 'Cups');
INSERT INTO "images" (id, product_name) VALUES (43, 'Coffee Mug');
INSERT INTO "images" (id, product_name) VALUES (44, 'Thermos');
INSERT INTO "images" (id, product_name) VALUES (45, 'Rice Cooker');
INSERT INTO "images" (id, product_name) VALUES (46, 'Spatula');
INSERT INTO "images" (id, product_name) VALUES (47, 'Coffee Maker');
INSERT INTO "images" (id, product_name) VALUES (48, 'Meal Prep Containers');
INSERT INTO "images" (id, product_name) VALUES (49, 'Lunch Box');
INSERT INTO "images" (id, product_name) VALUES (50, 'Banana Holder');
INSERT INTO "images" (id, product_name) VALUES (51, 'Corkscrew');
INSERT INTO "images" (id, product_name) VALUES (52, 'Sandwich Bags');
INSERT INTO "images" (id, product_name) VALUES (53, 'Aluminum Foil');
INSERT INTO "images" (id, product_name) VALUES (54, 'Plastic Wrap');
INSERT INTO "images" (id, product_name) VALUES (55, 'Tupperware Bowl');
INSERT INTO "images" (id, product_name) VALUES (56, 'Broccoliflower');
INSERT INTO "images" (id, product_name) VALUES (57, 'Cheese Wheel');
INSERT INTO "images" (id, product_name) VALUES (58, 'Protein Powder');
INSERT INTO "images" (id, product_name) VALUES (59, 'Plantain');
INSERT INTO "images" (id, product_name) VALUES (60, 'Unicorn Dust');
INSERT INTO "images" (id, product_name) VALUES (61, 'Oregano');
INSERT INTO "images" (id, product_name) VALUES (62, 'Banana');
INSERT INTO "images" (id, product_name) VALUES (63, 'Apple Juice');
INSERT INTO "images" (id, product_name) VALUES (64, 'Rubbing Alcohol');
INSERT INTO "images" (id, product_name) VALUES (65, 'Dietary Supplement');
INSERT INTO "images" (id, product_name) VALUES (66, 'Omega Three');
INSERT INTO "images" (id, product_name) VALUES (67, 'Whey Powder');
INSERT INTO "images" (id, product_name) VALUES (68, 'Apple');
INSERT INTO "images" (id, product_name) VALUES (69, 'Caffeine Pills');
INSERT INTO "images" (id, product_name) VALUES (70, 'Milk');
INSERT INTO "images" (id, product_name) VALUES (71, 'Hamster Food');
INSERT INTO "images" (id, product_name) VALUES (72, 'Cheesy Puffs');
INSERT INTO "images" (id, product_name) VALUES (73, 'Unfiltered Water');
INSERT INTO "images" (id, product_name) VALUES (74, 'Edible Forks');
INSERT INTO "images" (id, product_name) VALUES (75, 'Boxed Water');
INSERT INTO "images" (id, product_name) VALUES (76, 'Garden Gnome');
INSERT INTO "images" (id, product_name) VALUES (77, 'Riding Mower');
INSERT INTO "images" (id, product_name) VALUES (78, 'Hose');
INSERT INTO "images" (id, product_name) VALUES (79, 'Lawn Flamingo');
INSERT INTO "images" (id, product_name) VALUES (80, 'Metal Sickle');
INSERT INTO "images" (id, product_name) VALUES (81, 'Chainsaw');
INSERT INTO "images" (id, product_name) VALUES (82, 'Weed Trimmer');
INSERT INTO "images" (id, product_name) VALUES (83, 'Oscillating Sprinkler');
INSERT INTO "images" (id, product_name) VALUES (84, 'Sprinkler');
INSERT INTO "images" (id, product_name) VALUES (85, 'Bird Bath');
INSERT INTO "images" (id, product_name) VALUES (86, 'BBQ Lighter');
INSERT INTO "images" (id, product_name) VALUES (87, 'Weed Burner');
INSERT INTO "images" (id, product_name) VALUES (88, 'XL Lawn Chair');
INSERT INTO "images" (id, product_name) VALUES (89, 'Small Circular Fountain');
INSERT INTO "images" (id, product_name) VALUES (90, 'Patio Umbrella');
INSERT INTO "images" (id, product_name) VALUES (91, 'Wood Patio Table');
INSERT INTO "images" (id, product_name) VALUES (92, 'Jacuzzi');
INSERT INTO "images" (id, product_name) VALUES (93, 'Solar Panel');
INSERT INTO "images" (id, product_name) VALUES (94, 'Inflatable Pool');
INSERT INTO "images" (id, product_name) VALUES (95, 'Succulent Planter');
INSERT INTO "images" (id, product_name) VALUES (96, 'Pool Floatie');
INSERT INTO "images" (id, product_name) VALUES (97, 'Pool Noodle');
INSERT INTO "images" (id, product_name) VALUES (98, 'Plastic Rock Enclosure');
INSERT INTO "images" (id, product_name) VALUES (99, 'Astroturf');
INSERT INTO "images" (id, product_name) VALUES (100, '20 ft Metal Giraffe');




INSERT INTO "pictures" (id, url, "imageId") VALUES (1, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/black_leather_sofa.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/black_leather_sofa_2.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/black_leather_sofa_3.jpg', 1);
INSERT INTO "pictures" (id, url, "imageId") VALUES (2, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/mattress.jpg', 2);
INSERT INTO "pictures" (id, url, "imageId") VALUES (3, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/folding_table.jpg', 3);
INSERT INTO "pictures" (id, url, "imageId") VALUES (4, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/globe.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/globe_2.jpg', 4);
INSERT INTO "pictures" (id, url, "imageId") VALUES (5, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/bookshelf.jpg', 5);
INSERT INTO "pictures" (id, url, "imageId") VALUES (6, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Dining_table_for_two.jpg', 6);
INSERT INTO "pictures" (id, url, "imageId") VALUES (7, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/wood_dining_table.jpg', 7);
INSERT INTO "pictures" (id, url, "imageId") VALUES (8, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Softside_Waterbed_Inside.JPG', 8);
INSERT INTO "pictures" (id, url, "imageId") VALUES (9, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/beanbag.jpg', 9);
INSERT INTO "pictures" (id, url, "imageId") VALUES (10, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/nightstand.jpg', 10);
INSERT INTO "pictures" (id, url, "imageId") VALUES (11, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/desk_lamp.jpg', 11);
INSERT INTO "pictures" (id, url, "imageId") VALUES (12, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/mirror.JPG', 12);
INSERT INTO "pictures" (id, url, "imageId") VALUES (13, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Prze%25C5%259Bcierad%25C5%2582o.jpg', 13);
INSERT INTO "pictures" (id, url, "imageId") VALUES (14, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Summit_silk_bedding_comforter.jpg', 14);
INSERT INTO "pictures" (id, url, "imageId") VALUES (15, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Pillows_on_a_hotel_bed.jpg', 15);
INSERT INTO "pictures" (id, url, "imageId") VALUES (16, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Fern_dsc06699.jpg', 16);
INSERT INTO "pictures" (id, url, "imageId") VALUES (17, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/1990s_Mathmos_Astro.jpg', 17);
INSERT INTO "pictures" (id, url, "imageId") VALUES (18, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Shag.jpg', 18);
INSERT INTO "pictures" (id, url, "imageId") VALUES (19, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Disco_ball_in_home.jpg', 19);
INSERT INTO "pictures" (id, url, "imageId") VALUES (20, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/StrobeLight.jpg', 20);
INSERT INTO "pictures" (id, url, "imageId") VALUES (21, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/A_rebuilt_Terminator_2_pinball_machine.jpg', 21);
INSERT INTO "pictures" (id, url, "imageId") VALUES (22, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Mesanilo.jpg', 22);
INSERT INTO "pictures" (id, url, "imageId") VALUES (23, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Antique_chest_of_drawers_and_octagonal_table.jpg', 23);
INSERT INTO "pictures" (id, url, "imageId") VALUES (24, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Longcase_clock.JPG', 24);
INSERT INTO "pictures" (id, url, "imageId") VALUES (25, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/foosball.jpg', 25);
INSERT INTO "pictures" (id, url, "imageId") VALUES (26, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Aeron_chair_JN.jpg', 26);
INSERT INTO "pictures" (id, url, "imageId") VALUES (27, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Scented_candle.jpg', 27);
INSERT INTO "pictures" (id, url, "imageId") VALUES (28, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/pillow_PNG14219.jpg', 28);
INSERT INTO "pictures" (id, url, "imageId") VALUES (29, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Presse-ail_ik%25C3%25A9a_koncis_09.jpg', 29);
INSERT INTO "pictures" (id, url, "imageId") VALUES (30, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Digital_kitchen_timer.jpg', 30);
INSERT INTO "pictures" (id, url, "imageId") VALUES (31, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Plasticware_-_isolated.jpg', 31);
INSERT INTO "pictures" (id, url, "imageId") VALUES (32, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/SubZeroExt.jpg', 32);
INSERT INTO "pictures" (id, url, "imageId") VALUES (33, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Ice_cream_fork%252C_Shreve_%2526_Company%252C_Iris_service%252C_silver%252C_1903-1917.jpg', 33);
INSERT INTO "pictures" (id, url, "imageId") VALUES (34, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Salt_shaker_on_white_background.jpg', 34);
INSERT INTO "pictures" (id, url, "imageId") VALUES (35, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/moist_toilette.jpg', 35);
INSERT INTO "pictures" (id, url, "imageId") VALUES (36, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Holzzahnstocher.jpg', 36);
INSERT INTO "pictures" (id, url, "imageId") VALUES (37, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/lossy-page1-1280px-Consumer_Reports_-_Kenmore_microwave_oven.tif.jpg', 37);
INSERT INTO "pictures" (id, url, "imageId") VALUES (38, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/ElectricBlender.jpg', 38);
INSERT INTO "pictures" (id, url, "imageId") VALUES (39, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Grilling.jpg', 39);
INSERT INTO "pictures" (id, url, "imageId") VALUES (40, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Baking_glove.jpg', 40);
INSERT INTO "pictures" (id, url, "imageId") VALUES (41, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Afwasmiddel_Una_Aldi.JPG,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/dish_soap.jpg', 41);
INSERT INTO "pictures" (id, url, "imageId") VALUES (42, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Plastic_cup-2.jpg', 42);
INSERT INTO "pictures" (id, url, "imageId") VALUES (43, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Mug_of_Tea.JPG', 43);
INSERT INTO "pictures" (id, url, "imageId") VALUES (44, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Thermos.JPG', 44);
INSERT INTO "pictures" (id, url, "imageId") VALUES (45, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Zojirushi_NS-JSS10_with_scoop_20050801.jpg', 45);
INSERT INTO "pictures" (id, url, "imageId") VALUES (46, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Kitchen-spatula.jpg', 46);
INSERT INTO "pictures" (id, url, "imageId") VALUES (47, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/lossy-page1-3819px-Consumer_Reports_-_Zojirushi_coffeemaker_alt.tif.jpg', 47);
INSERT INTO "pictures" (id, url, "imageId") VALUES (48, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Tupperware_translucent_blue.jpg', 48);
INSERT INTO "pictures" (id, url, "imageId") VALUES (49, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/lunch_box.jpg', 49);
INSERT INTO "pictures" (id, url, "imageId") VALUES (50, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/banana_holder.jpg', 50);
INSERT INTO "pictures" (id, url, "imageId") VALUES (51, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Spiral-Korkenzieher.jpg', 51);
INSERT INTO "pictures" (id, url, "imageId") VALUES (52, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Ziplock.jpg', 52);
INSERT INTO "pictures" (id, url, "imageId") VALUES (53, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Aluminium_foil_micrometer.jpg', 53);
INSERT INTO "pictures" (id, url, "imageId") VALUES (54, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Pvc-Film.jpg', 54);
INSERT INTO "pictures" (id, url, "imageId") VALUES (55, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Tupperware_Ultraplus.JPG', 55);
INSERT INTO "pictures" (id, url, "imageId") VALUES (56, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Fractal_Broccoli.jpg', 56);
INSERT INTO "pictures" (id, url, "imageId") VALUES (57, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Berkswell_cheese.jpg', 57);
INSERT INTO "pictures" (id, url, "imageId") VALUES (58, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Apollo_Vanilla_Protein_Powder.jpg', 58);
INSERT INTO "pictures" (id, url, "imageId") VALUES (59, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Plantains.jpg', 59);
INSERT INTO "pictures" (id, url, "imageId") VALUES (60, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Berkswell_cheese.jpg', 60);
INSERT INTO "pictures" (id, url, "imageId") VALUES (61, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/oregano.jpg', 61);
INSERT INTO "pictures" (id, url, "imageId") VALUES (62, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Banana.arp.750pix.jpg', 62);
INSERT INTO "pictures" (id, url, "imageId") VALUES (63, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Red_Apple.jpg', 63);
INSERT INTO "pictures" (id, url, "imageId") VALUES (64, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Rubbing_alcohol.JPG', 64);
INSERT INTO "pictures" (id, url, "imageId") VALUES (65, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Spirulina_tablets.jpg', 65);
INSERT INTO "pictures" (id, url, "imageId") VALUES (66, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Fish_Oil_Capsules.jpg', 66);
INSERT INTO "pictures" (id, url, "imageId") VALUES (67, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Apollo_Vanilla_Protein_Powder.jpg', 67);
INSERT INTO "pictures" (id, url, "imageId") VALUES (68, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Red_Apple.jpg', 68);
INSERT INTO "pictures" (id, url, "imageId") VALUES (69, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/kevins_caffeine_pills.jpg', 69);
INSERT INTO "pictures" (id, url, "imageId") VALUES (70, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/22-07-2017_Carton_of_UHT_Milk_of_Matinal_brand.JPG', 70);
INSERT INTO "pictures" (id, url, "imageId") VALUES (71, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Hamster_Food.JPG', 71);
INSERT INTO "pictures" (id, url, "imageId") VALUES (72, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Cheese_puffs.jpg', 72);
INSERT INTO "pictures" (id, url, "imageId") VALUES (73, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Sparkling-bottled-water.jpg', 73);
INSERT INTO "pictures" (id, url, "imageId") VALUES (74, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/edible_fork.jpg', 74);
INSERT INTO "pictures" (id, url, "imageId") VALUES (75, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/box_water_add_water.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/soggy_box.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/just_add_water.jpg,', 75);
INSERT INTO "pictures" (id, url, "imageId") VALUES (76, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/German_garden_gnome.jpg', 76);
INSERT INTO "pictures" (id, url, "imageId") VALUES (77, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/2007_swifts_creek_lawnmower_races04_edit.jpg', 77);
INSERT INTO "pictures" (id, url, "imageId") VALUES (78, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Gucci_Garden_Hose_%2524155.jpg', 78);
INSERT INTO "pictures" (id, url, "imageId") VALUES (79, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Featherstone-flamingos.jpg,https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Flocked_5-11-14d_%252814559768115%2529.jpg', 79);
INSERT INTO "pictures" (id, url, "imageId") VALUES (80, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Sickle_without_background.jpg', 80);
INSERT INTO "pictures" (id, url, "imageId") VALUES (81, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Chainsaw_ms280c_1.jpg', 81);
INSERT INTO "pictures" (id, url, "imageId") VALUES (82, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Rasentrimmer%252C_String_trimmer.JPG', 82);
INSERT INTO "pictures" (id, url, "imageId") VALUES (83, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Oscillating_Sprinkler.jpg', 83);
INSERT INTO "pictures" (id, url, "imageId") VALUES (84, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Impact_Sprinkler_Mechanism_2.jpg', 84);
INSERT INTO "pictures" (id, url, "imageId") VALUES (85, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Impact_Sprinkler_Mechanism_2.jpg', 85);
INSERT INTO "pictures" (id, url, "imageId") VALUES (86, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/bbq_lighter.jpg', 86);
INSERT INTO "pictures" (id, url, "imageId") VALUES (87, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/weed_burner.jpg', 87);
INSERT INTO "pictures" (id, url, "imageId") VALUES (88, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Lawn_chairs_%2528Unsplash%2529.jpg', 88);
INSERT INTO "pictures" (id, url, "imageId") VALUES (89, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Halifax_NS-02396_-_Small_Fountain_%252828446642293%2529.jpg', 89);
INSERT INTO "pictures" (id, url, "imageId") VALUES (90, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/640px-Garden_patio_umbrella.jpg', 90);
INSERT INTO "pictures" (id, url, "imageId") VALUES (91, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/1024px-2008-05-30_Glass_table_with_chairs_on_patio.jpg', 91);
INSERT INTO "pictures" (id, url, "imageId") VALUES (92, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Spa_jardin.jpg', 92);
INSERT INTO "pictures" (id, url, "imageId") VALUES (93, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/solar_panel.jpg', 93);
INSERT INTO "pictures" (id, url, "imageId") VALUES (94, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/1024px-Inflatable_Pool_%25287674190024%2529.jpg', 94);
INSERT INTO "pictures" (id, url, "imageId") VALUES (95, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Flickr_-_brewbooks_-_Succulent_Pot.jpg', 95);
INSERT INTO "pictures" (id, url, "imageId") VALUES (96, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/645px-Pool_Noodles_%25289733355071%2529.jpg', 96);
INSERT INTO "pictures" (id, url, "imageId") VALUES (97, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/645px-Pool_Noodles_%25289733355071%2529.jpg', 97);
INSERT INTO "pictures" (id, url, "imageId") VALUES (98, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/7721355524_8e83e14c09_z.jpg', 98);
INSERT INTO "pictures" (id, url, "imageId") VALUES (99, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Astroturf.jpg', 99);
INSERT INTO "pictures" (id, url, "imageId") VALUES (100, 'https://s3.us-east-2.amazonaws.com/photogallerydev22/Frontend+Pictures/Giraffes_in_Edinburgh_-_geograph.org.uk_-_208593.jpg', 100);
